### ISSUE TITLE
Mouse Hover

### ISSUE THREAD

**Issue by GreenArrow18** [Insality/druid#64]
I am getting an immediate mouse_hover callback for all buttons upon starting, even if the mouse is not inside any button yet.

Expected: the callback is only triggered when the mouse goes inside the button's zone.
Tested on: Defold 1.2.169 Windows 10 desktop

Suggestion: is it possible to have separate callbacks instead, like:
on_mouse_enter
on_mouse_leave

? Use case is for example, I would like to change the color/image when the mouse enters the button's area, then revert back to old/original state when it leaves. Or is this already possible?

Thanks.

**Comment by Insality** [comment]
Hello! Thanks for suggestion and point on hover bug.

Right, mouse_hover has wrong default state, so it was behaviour with callbacks upon starting.

_hover_ and _mouse_hover_ callbacks have next params: (self, state). Where state is boolean flag of hover state. You can use it instead of _on_mouse_enter_ and _on_mouse_leaver_

Released 0.4.2 with this bugfix: https://github.com/Insality/druid/archive/0.4.2.zip

Thanks for reporting!

**Comment by GreenArrow18** [comment]
This works great now. Thanks!
